version: '3.5'

name: context
services:
  backend:
    image: node:16-slim
    volumes:
      - ../..:/app
    working_dir: /app/server
    environment:
      PORT: 80
      PUBLIC_MULTIADDR: "/dns/context.local/tcp/443/wss"
      DEBUG: "libp2p:*"
    command: npm run run
    networks:
      main:
    restart: always

  front:
    image: node:16-slim
    volumes:
      - ../..:/app
    working_dir: /app/web/lifecycle
    environment:
      PORT: 80
    command: npm run serve
    networks:
      main:
    restart: always

  nginx:
    container_name: context_nginx
    image: nginx
    networks:
      main:
      host_local:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5005:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - backend
      - front
    links:
      - backend
      - front

networks:
  main:
    driver: bridge
  host_local:
    external: true
