# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: build app
        run: |
          npm i
          npm run ci

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: web docker
        working-directory: ./web
        run: |
          docker build . -f web.dockerfile -t ${{ IMAGE_NAME }}
          docker push ${{ IMAGE_NAME }}
        env:
          IMAGE_NAME: ghcr.io/co-text/web:latest


      - name: server docker
        working-directory: ./server
        run: |
          docker build . -f server.dockerfile -t ${{ IMAGE_NAME }}
          docker push ${{ IMAGE_NAME }}
        env:
          IMAGE_NAME: ghcr.io/co-text/server:latest
        
